baseURL = "http://example.org/"
languageCode = "en-us"
title = "//el-uhu"
theme = "bulma-base"

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    title = "//el-uhu"
    description = "SCIENCE | TEACHING | DATAVIS | MISC"
    weight = 1
    about = """\
Hi! My name is **Lukas Hutter** and I'm a scientist, teacher and webdesigner.\n
As a scientist, I'm interested in the Origin of Life, chemical computers and computation in general.\n
"""

    [language.en.newsletter]
      title = "Subscribe"


[params.logo]
    mobile = "/img/logo.svg"
    standard  = "/img/logo.svg"
    notext = "/img/logo.svg"
    heroImg = "/img/luki-full.jpg"

[taxonomies]
  category = "categories"
  tag = "tags"
  class = "classes"
  nativespeaker = "nativespeakers"
